### ISSUE TITLE
[Feature request] Add Github profile link

### ISSUE THREAD

**Issue by ematipico** [delucis/astro-badge#16]
It would be nice to have a GitHub link somewhere.

**Comment by delucis** [comment]
Do you mean to a contributor’s profile? We do have one next to their user name on the individual pages. For example: https://astro.badg.es/v1/contributor/ematipico/
<img width="350" alt="image" src="https://github.com/delucis/astro-badge/assets/357379/d012f97d-951d-49ad-9842-3c3ca22ac641">

I guess this issue shows it’s not so clear 😅 

Mark’s redesign will make this more obvious:
<img width="471" alt="image" src="https://github.com/delucis/astro-badge/assets/357379/41b6e17c-54bd-465a-8ce3-2662675de631">

**Comment by ematipico** [comment]
Oh wow!! Yes I complete missed that! My eye was focused to the actual badge and information, I completely overlooked the title. 

Closing then :D
