### ISSUE TITLE
Request to resize default badge

### ISSUE THREAD

**Issue by torn4dom4n** [delucis/astro-badge#20]
Hello, I have a request to resize the default badge. I must add HTML img tag in order for this badge to be the same size as other badges like Netlify or GitHub CI. For example, add this to README:

```md
[![Built with Astro](https://astro.badg.es/v1/built-with-astro.svg)](https://astro.build) [![Netlify Build](https://api.netlify.com/api/v1/badges/c882c9a0-e5f6-4066-89fd-c07c7ca2efdf/deploy-status)](https://app.netlify.com/sites/astro-multiverse/deploys)
```

The README look like this:
[![Built with Astro](https://astro.badg.es/v1/built-with-astro.svg)](https://astro.build) [![Netlify Build](https://api.netlify.com/api/v1/badges/c882c9a0-e5f6-4066-89fd-c07c7ca2efdf/deploy-status)](https://app.netlify.com/sites/astro-multiverse/deploys)

You can see the BWA badge is bigger than Netlify badge. So I need a HTML img tag with height:

```md
<p>
  <a href="https://astro.build">
    <img src="https://astro.badg.es/v1/built-with-astro.svg" alt="Built with Astro" height="20">
  </a>
  <a href="https://github.com/AREA44/astro-research-theme/actions/workflows/pages.yml">
    <img src="https://github.com/AREA44/astro-research-theme/actions/workflows/pages.yml/badge.svg" alt="Deploy Astro site to Pages">
  </a>
  <a href="https://app.netlify.com/sites/astro-multiverse/deploys">
    <img src="https://api.netlify.com/api/v1/badges/c882c9a0-e5f6-4066-89fd-c07c7ca2efdf/deploy-status" alt="Netlify Status">
  </a>
</p>
```
The result looks better:
<p>
  <a href="https://astro.build">
    <img src="https://astro.badg.es/v1/built-with-astro.svg" alt="Built with Astro" height="20">
  </a>
  <a href="https://github.com/AREA44/astro-research-theme/actions/workflows/pages.yml">
    <img src="https://github.com/AREA44/astro-research-theme/actions/workflows/pages.yml/badge.svg" alt="Deploy Astro site to Pages">
  </a>
  <a href="https://app.netlify.com/sites/astro-multiverse/deploys">
    <img src="https://api.netlify.com/api/v1/badges/c882c9a0-e5f6-4066-89fd-c07c7ca2efdf/deploy-status" alt="Netlify Status">
  </a>
</p>

**Comment by delucis** [comment]
We probably shouldn't resize the existing sizes given some people are already using them and expect those sizes, but we could definitely add a smaller size like this!

Would you be interested in making a PR?

**Comment by torn4dom4n** [comment]
@delucis I can do it. But before start, what is the name of new size? We have `small`, `medium` and `large`. BTW, can I change default `copy` with new size at https://astro.badg.es/bwa/? It'll be easy for new people to copy & pate it.

**Comment by delucis** [comment]
How about `extra-small` or `tiny`?

And sure, you can update the copy snippets if you like!
